### PR TITLE
Feature - Support user authentication

### LINKED ISSUE #1: User Authentication
Hi, 

I'm opening this issue because Zendesk released the authentication for the new Messaging SDK (https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/android/advanced_integration/#authentication)

It could be great to implement it in this package too :)

### PR DESCRIPTION
**Pull request by tspoke**
This PR is still in **WIP** but it will add authentication support for Zendesk (fix #1)

[x] Android support
[x] iOS support
[x] Documentation

### Authentication

**Usage with helpers :** 

```dart
Future<ZendeskLoginResponse> login() async {
   final String jwt = await ...; // get your JWT
   return ZendeskMessaging.loginUser(jwt: jwt);
}

Future<void> logout() async {
   return ZendeskMessaging.logoutUser();
}
```

**Usage with default methods and callbacks :** 

```dart
Future<void> login() async {
   final String jwt = await ...; // get your JWT
   await ZendeskMessaging.loginUserCallbacks(
      jwt: jwt, 
      onSuccess: (id, externalId) {
          // handle success
      }, 
      onFailure: () {
          // handle failure
      },
   );
}

Future<void> logout() async {
   await ZendeskMessaging.logoutUserCallbacks(
      onSuccess: () {
          // handle success
      }, 
      onFailure: () {
          // handle failure
      },
   );
}
```

### Observers

I added some channel methods to be able to watch for success/failure. I updated the example too to display them.

You can attach a global observer to catch messages from native platforms : 

```dart

ZendeskMessaging.setMessageHandler((type, arguments) {
     // type is an enum, see ZendeskMessagingMessageType
});

```

### CODE REVIEW

**Comment by tspoke** [comment]
Thanks for the merge. Can you publish a new version on pub.dev ?

**Comment by tspoke** [comment]
@chyiiiiiiiiiiii up on this one for the tag :)

**Comment by chyiiiiiiiiiiii** [comment]
@tspoke I'll publish. Please, could you check some issues for me?

**Comment by tspoke** [comment]
The two issues are missing a lot of explaination. I'm running a copy of this PR on my side with a production app (iOS and android) and everything is fine.

**Pull request merged**
